workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd udaan_app
          flutter pub get
      - name: Build APK
        script: |
          cd udaan_app
          flutter build apk --release
    artifacts:
      - udaan_app/build/app/outputs/flutter-apk/*.apk
